version: "3.9"

networks:
  vpn-app:
    driver: bridge

services:
  # NGINX web server
  nginx:
    image: nginx
    container_name: nginx
    volumes:
#      - ./nginx/custompasswd:/etc/nginx/custompasswd
      - ./nginx/src:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/templates:/etc/nginx/templates
      - ./.app_data/nginx_log:/var/log/nginx
      - ./.app_data/vpn:/usr/share/nginx/html/vpn
    ports:
      - "0.0.0.0:80:80"
    networks:
      - vpn-app
    restart: unless-stopped

  # VPN server
  open-vpn-node-1:
    image: alekslitvinenk/openvpn
    container_name: open-vpn-node-1
    privileged: true
    environment:
      HOST_ADDR: ${VPN_ADDRESS}
      HOST_TUN_PORT: ${VPN_PORT}
    ports:
      - "0.0.0.0:${VPN_PORT}:1194/udp"
    networks:
      vpn-app:
    restart: unless-stopped
